name: Main

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.17', '1.18', '1.19', '1.20', '1.21', '1.22']
        # See supported Go release schedule at https://golang.org/doc/devel/release.html
        #
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}


        #- name: Install dependencies
        #  run: go mod tidy

        #- name: Build
        #  run: go build -v ./...

    - name: Demo
      run: go run demo.go
